(defun compilation-if (exp env fenv nomf)
  (let ((sinon (gensym "sinon"))
	(finSi (gensym "finSi")))
    (append (compilation (car exp) env fenv nomf)  
	    '((CMP :R0 (:DIESE nil)))
	    `((JEQ (@ ,sinon)))
	    (compilation (cadr exp) env fenv nomf) 
	    `((JMP (@ ,finSi)))
	    `((@ ,sinon))  
	    (compilation (caddr exp) env fenv nomf)
	    `((@ ,finSi)))
    )
  )